config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"
  resources :questions, only: [:index, :new]
  resources :users, only: [:show]
  resources :scores, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
  serialize :result
  serialize :questions
  serialize :answer_text
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true, length: { maximum: 8 }
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_user

  def index
   
  end

  def new
    @questions = Question.order(Arel.sql("RAND()")).limit(10)
    gon.questions = @questions
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def create
    Score.create(score_params)
  end

  private
    def score_params
      params.permit(result: [], questions: [], answer_text: []).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @scores = Score.includes(:user).where(user_id: current_user.id).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KanjiQuiz
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/questions/index.html.haml
= render 'shared/header'

.main
  .main-body
    %P.main-body__message
      難読漢字クイズに挑戦！
    %p.main-body__secmessage
      クイズをはじめる⬇︎
    .main-body__button
      = link_to '開始', new_question_path

app/views/questions/new.html.haml
= render 'shared/header'

.major
  .major-box
    %h1.major-box__message
      #text_content
        何と読む？
    .major-box__question
      #text_question

.footer
  .footer-box
    .footer-box__choice
      #text_select

app/views/shared/_error_messages.html.haml
- if user.errors.any?
  - unless user.valid?
    - if errors = user.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li.error_message
            =error

app/views/shared/_header.html.haml
.header
  .header-list
    .header-list__user
      = link_to user_path(current_user.id) do
        = @user.nickname
    .header-list__logo
      難読漢字クイズ
    .header-list__icon
      = link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/users/show.html.haml
.score-header
  .score-header_title
    = @user.nickname
    さんの過去の成績
  .score-header_back
    = link_to "←戻る", root_path

.score-body
  -@scores.each do |score|
    .score-time
      = l score.created_at
    %table
      %tr
        %th
          問題
        %td
          = score.questions[0]
        %td
          = score.questions[1]
        %td
          = score.questions[2]
        %td
          = score.questions[3]
        %td
          = score.questions[4]
        %td
          = score.questions[5]
        %td
          = score.questions[6]
        %td
          = score.questions[7]
        %td
          = score.questions[8]
        %td
          = score.questions[9]
      %tr
        %th
          答え
        %td
          = score.answer_text[0]
        %td
          = score.answer_text[1]
        %td
          = score.answer_text[2]
        %td
          = score.answer_text[3]
        %td
          = score.answer_text[4]
        %td
          = score.answer_text[5]
        %td
          = score.answer_text[6]
        %td
          = score.answer_text[7]
        %td
          = score.answer_text[8]
        %td
          = score.answer_text[9]
      %tr
        %th
          正誤
        %td
          = score.result[0]
        %td
          = score.result[1]
        %td
          = score.result[2]
        %td
          = score.result[3]
        %td
          = score.result[4]
        %td
          = score.result[5]
        %td
          = score.result[6]
        %td
          = score.result[7]
        %td
          = score.result[8]
        %td
          = score.result[9]

.score-footer
  %span
    &copy; 2020 難読漢字クイズ